INFO:root:Processing AGV schedule request
INFO:root:Processing AGV schedule request
INFO:root:Processing AGV schedule request
INFO:root:Processing AGV schedule request
INFO:root:Processing AGV schedule request
INFO:root:Processing AGV schedule request
INFO:root:Processing AGV schedule request
INFO:root:Processing AGV schedule request
INFO:root:Processing AGV schedule request
INFO:root:Processing AGV schedule request
INFO:root:Processing AGV schedule request
INFO:root:Processing AGV schedule request
INFO:root:Processing AGV schedule request
INFO:root:Processing AGV schedule request
INFO:root:Processing AGV schedule request
INFO:root:Processing AGV schedule request
INFO:root:Processing AGV schedule request
INFO:root:Processing AGV schedule request
INFO:root:Processing AGV schedule request
INFO:root:Processing AGV schedule request
INFO:root:Processing AGV schedule request
INFO:root:Processing AGV schedule request
INFO:root:Processing AGV schedule request
INFO:root:Processing AGV schedule request
INFO:root:Processing AGV schedule request
INFO:root:Processing AGV schedule request
INFO:root:Processing AGV schedule request
INFO:root:Processing AGV schedule request
INFO:root:Processing AGV schedule request
ERROR:root:Error processing scheduler: 'Battery (mins left)'
Traceback (most recent call last):
  File "C:\Users\Aishwarya\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\indexes\base.py", line 3791, in get_loc
    return self._engine.get_loc(casted_key)
  File "index.pyx", line 152, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 181, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Battery (mins left)'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\agv-hackathon\agv-scheduler-api\main.py", line 143, in process_scheduler
  File "C:\Users\Aishwarya\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\series.py", line 1040, in __getitem__
    return self._get_value(key)
  File "C:\Users\Aishwarya\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\series.py", line 1156, in _get_value
    loc = self.index.get_loc(label)
  File "C:\Users\Aishwarya\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\indexes\base.py", line 3798, in get_loc
    raise KeyError(key) from err
KeyError: 'Battery (mins left)'

ERROR:root:API Error: 'Battery (mins left)'
INFO:root:Processing AGV schedule request
INFO:root:Processing AGV schedule request
INFO:root:Processing AGV schedule request
INFO:root:Processing AGV schedule request
INFO:root:Processing AGV schedule request
INFO:root:Processing AGV schedule request
INFO:root:Processing AGV schedule request
INFO:root:Processing AGV schedule request
INFO:root:Processing AGV schedule request
INFO:root:Processing AGV schedule request
INFO:root:Processing AGV schedule request
INFO:root:Processing AGV schedule request
INFO:root:Processing AGV schedule request
INFO:root:Processing AGV schedule request
INFO:root:Processing AGV schedule request
INFO:root:Processing AGV schedule request
INFO:root:Processing AGV schedule request
